import Hero from './Hero'
import Footer from './Footer'
import Navbar from './Navbar'
import CustomFilter from './CustomFilter'
import SearchBar from './SearchBar'
import SearchManufactures from './SearchManufactures'
import BikeDetails from './BikeDetails'
import BikeCard from './BikeCard'
export {BikeCard,BikeDetails,SearchManufactures,Hero,SearchBar,CustomFilter, Footer, Navbar}